import { create } from "zustand";
import { buildAiContext } from "@/lib/ai/context";
import { CHART_REGISTRY, type ChartId } from "@/lib/ai/chartRegistry";

let msgSeq = 0;
const nextMsgId = () => `AIM-${++msgSeq}`;

export interface AiMessage {
  id: string;
  role: "user" | "model";
  text: string;
  /** Set when this turn was auto-generated by a chart's "Ask AI" button, so the UI can render it as a compact chip instead of a full chat bubble. */
  chartLabel?: string;
}

export interface WagonAskSlice {
  seq: number;
  uid: string;
  netT: number;
  utilizationPct: number;
  controlMode: string;
  spillFlag: boolean;
  overloadFlag: boolean;
}

interface AiStoreState {
  open: boolean;
  messages: AiMessage[];
  streaming: boolean;
  error: string | null;

  togglePanel: () => void;
  openPanel: () => void;
  closePanel: () => void;
  clear: () => void;
  send: (text: string) => Promise<void>;
  askAboutChart: (chartId: ChartId) => Promise<void>;
  /** Recent Wagons Table row click (Phase 4c) — pre-seeds Ask AI with one specific wagon's record instead of the whole table. */
  askAboutWagon: (wagon: WagonAskSlice) => Promise<void>;
}

async function streamChat(
  history: AiMessage[],
  scope: ChartId | undefined,
  onDelta: (text: string) => void,
): Promise<string | null> {
  const context = buildAiContext(scope);
  const res = await fetch("/api/ai/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      messages: history.map((m) => ({ role: m.role, text: m.text })),
      context,
    }),
  });

  const contentType = res.headers.get("content-type") ?? "";
  if (!res.ok || contentType.includes("application/json")) {
    const data = await res.json().catch(() => ({ error: "AI assistant unavailable — console unaffected." }));
    return data.error ?? "AI assistant unavailable — console unaffected.";
  }
  if (!res.body) return "AI assistant unavailable — console unaffected.";

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buf = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += decoder.decode(value, { stream: true });
    const frames = buf.split("\n\n");
    buf = frames.pop() ?? "";
    for (const frame of frames) {
      const line = frame.trim();
      if (!line.startsWith("data:")) continue;
      try {
        const parsed = JSON.parse(line.slice(5).trim());
        if (parsed.text) onDelta(parsed.text);
        if (parsed.done) return null;
      } catch {
        // partial frame — ignore, next read completes it
      }
    }
  }
  return null;
}

export const useAiStore = create<AiStoreState>((set, get) => ({
  open: false,
  messages: [],
  streaming: false,
  error: null,

  togglePanel: () => set((s) => ({ open: !s.open })),
  openPanel: () => set({ open: true }),
  closePanel: () => set({ open: false }),
  clear: () => set({ messages: [], error: null }),

  send: async (text: string) => {
    if (!text.trim() || get().streaming) return;
    const userMsg: AiMessage = { id: nextMsgId(), role: "user", text };
    const modelMsg: AiMessage = { id: nextMsgId(), role: "model", text: "" };
    set((s) => ({ messages: [...s.messages, userMsg, modelMsg], streaming: true, error: null }));

    const history = [...get().messages.filter((m) => m.id !== modelMsg.id)];
    const err = await streamChat(history, undefined, (delta) => {
      set((s) => ({
        messages: s.messages.map((m) => (m.id === modelMsg.id ? { ...m, text: m.text + delta } : m)),
      }));
    }).catch((e) => (e instanceof Error ? e.message : "AI assistant unavailable — console unaffected."));

    set((s) => ({
      streaming: false,
      error: err,
      messages: err
        ? s.messages.map((m) => (m.id === modelMsg.id && !m.text ? { ...m, text: err } : m))
        : s.messages,
    }));
  },

  askAboutChart: async (chartId: ChartId) => {
    if (get().streaming) return;
    const def = CHART_REGISTRY[chartId];
    set({ open: true });
    const prompt = `Give a 3-sentence summary of the "${def.label}" view from the attached chart data, then wait for follow-up questions.`;
    const userMsg: AiMessage = { id: nextMsgId(), role: "user", text: prompt, chartLabel: def.label };
    const modelMsg: AiMessage = { id: nextMsgId(), role: "model", text: "" };
    set((s) => ({ messages: [...s.messages, userMsg, modelMsg], streaming: true, error: null }));

    const history = [...get().messages.filter((m) => m.id !== modelMsg.id)];
    const err = await streamChat(history, chartId, (delta) => {
      set((s) => ({
        messages: s.messages.map((m) => (m.id === modelMsg.id ? { ...m, text: m.text + delta } : m)),
      }));
    }).catch((e) => (e instanceof Error ? e.message : "AI assistant unavailable — console unaffected."));

    set((s) => ({
      streaming: false,
      error: err,
      messages: err
        ? s.messages.map((m) => (m.id === modelMsg.id && !m.text ? { ...m, text: err } : m))
        : s.messages,
    }));
  },

  askAboutWagon: async (wagon) => {
    if (get().streaming) return;
    set({ open: true });
    const flags = [wagon.spillFlag && "a spill", wagon.overloadFlag && "an overload"].filter(Boolean).join(" and ");
    const label = `Wagon #${wagon.seq}`;
    const prompt = `Tell me about ${label} (UID ${wagon.uid}): net ${wagon.netT.toFixed(2)} t, ${wagon.utilizationPct.toFixed(2)}% utilization, loaded in ${wagon.controlMode} mode${flags ? `, flagged for ${flags}` : ", no flags"}. Explain what this means in plain terms.`;
    const userMsg: AiMessage = { id: nextMsgId(), role: "user", text: prompt, chartLabel: label };
    const modelMsg: AiMessage = { id: nextMsgId(), role: "model", text: "" };
    set((s) => ({ messages: [...s.messages, userMsg, modelMsg], streaming: true, error: null }));

    const history = [...get().messages.filter((m) => m.id !== modelMsg.id)];
    const err = await streamChat(history, "recent-wagons", (delta) => {
      set((s) => ({
        messages: s.messages.map((m) => (m.id === modelMsg.id ? { ...m, text: m.text + delta } : m)),
      }));
    }).catch((e) => (e instanceof Error ? e.message : "AI assistant unavailable — console unaffected."));

    set((s) => ({
      streaming: false,
      error: err,
      messages: err
        ? s.messages.map((m) => (m.id === modelMsg.id && !m.text ? { ...m, text: err } : m))
        : s.messages,
    }));
  },
}));
